---
title: JC Treacy
email: your-email@domain.com
url: https://hello-heydavid.github.io
baseurl: "/jc-treacy-2"
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
keywords: your keywords, separated by commas
skills: I help business owners earn a passive income. || Connecting people through
  Leadership Development, Philanthropy, and Social Impact ||
meta-author: LastName FirstName
google-verify: ''
bing-verify: ''
disqus-shortname: myshortname
color:
  primary: 18bc9c
  secondary: 2c1376
  secondary-dark: '233140'
about:
  title: When you create strong relationships, you attract great people
  first-description: "We are still working on the site at the moment but for now here's
    the \"Clif's Notes\" version.\r\n​\r\nDuring pursuit of a Master's degree I developed
    a passion for training and educating. \r\n​\r\n"
  second-description: "This started my work with children under the age of 12. For
    10 years I honed my communication and leadership skills. I was fortunate enough
    to have some pretty great leaders to follow. \r\n​\r\nWhen I made the change to
    sales and marketing I knew something was missing. That guidance of a leader. I
    was lucky enough to seek a mentor and once him and his wife took my fiance and
    I on we never looked back.\r\n​\r\nCheck out Blue.social\r\n"
  button-url: https://github.com/jeromelachaud/freelancer-theme
  button-text: Download Theme
contact:
  title: Contact Me
portfolio:
  title: ''
footer:
  location: Location
  credits: Credits
social-list:
- title: envelope
  url: mailto:Treacy.jc@gmail.com
- title: phone
  url: tel:631-662-1044
- title: whatsapp
  url: https://wa.me/6316621044
- title: star
  url: https://www.linkedin.com/in/jc-treacy
- title: twitter
  url: https://twitter.com/treacyjc
address: Long Island, NY
credits: Special thanks to Sheng for introducing me to this platform.
markdown: kramdown
permalink: pretty
